name: Build FPM

on:
  push:
    branches:
      - main
    paths:
      - '**/*.cpp'
      - '**/*.hpp'
      - '**/*.c'
      - '**/*.h'
      - '**/*.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.cpp'
      - '**/*.hpp'
      - '**/*.c'
      - '**/*.h'
      - '**/*.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Configure
      run: curl https://github.com/nlohmann/json/releases/download/v3.11.3/json.hpp -O
    - name: Compile FPM
      run: g++ ./fpm.cpp -o fpm
    - name: Upload FPM binary
      uses: actions/upload-artifact@v4
      with:
        name: fpm-binary
        path: ./fpm
